// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AssignmentController from "./assignment_controller"
application.register("assignment", AssignmentController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ViewModeController from "./view_mode_controller"
application.register("view-mode", ViewModeController)
